# Generated by Django 4.0.5 on 2022-06-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beak', '0002_openinghours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openinghours',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]),
        ),
    ]
