# Generated by Django 4.0.5 on 2022-07-07 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beak', '0003_alter_openinghours_weekday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='google_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
