# Generated by Django 4.0.5 on 2022-07-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beak', '0004_alter_place_google_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('number', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('places', models.ManyToManyField(blank=True, to='beak.place')),
            ],
        ),
        migrations.CreateModel(
            name='General_Location',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('places', models.ManyToManyField(blank=True, to='beak.place')),
            ],
        ),
    ]
